Repository puppetlabs/litmusimage, pull requests merged in 2023-08, with the labels that each got.

#53 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#54 (gh-36) - add missing iproute package
  .github/workflows/build_dockerfiles.yml
  .github/workflows/update_images.yml
  yum_systemd_dockerfile
Labels: bugfix

#55 (maint) - README Updates
  README.md
Labels: maintenance

#56 (maint) - update nightly.yml image matrix
  .github/workflows/nightly.yml
Labels: maintenance

#48 Add newer oraclelinux images
  .github/workflows/build_dockerfiles.yml
  .github/workflows/nightly.yml
  .github/workflows/update_images.yml
  README.md
Labels: feature

#58 Remove duplicate oraclelinux 7 table row from README
  README.md
Labels: maintenance, community

#59 (maint) - Add Amazon Linux 2 & Fedora 36
  .github/workflows/build_dockerfiles.yml
  .github/workflows/nightly.yml
  .github/workflows/update_images.yml
  README.md
Labels: feature

#60 (maint) - Update instances of actions/checkout
  .github/workflows/build_dockerfiles.yml
  .github/workflows/nightly.yml
  .github/workflows/update_images.yml
Labels: maintenance

#61 (CAT-1320) Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#62 Build image for Debian 12 (bookworm)
  .github/workflows/build_dockerfiles.yml
Labels: community

#63 (MAINT) Adding Debian 12 image build as part of github Actions
  .github/workflows/update_images.yml
Labels: maintenance
