Repository puppetlabs/litmusimage, pull requests merged in 2024-06, with the labels that each got.

#90 (CAT-1901) - Handle 'No URLs in mirrorlist' error for 'appstream' repo in CentOS 8
  yum_systemd.dockerfile
Labels: bugfix

#86 Add remaining puppet-agent supported ARM64 platforms
  images.json
Labels: feature

#91 (maint) Update labeller.yml to pull_request
  .github/workflows/labeller.yml
Labels: maintenance
